Importing Numpy


In [1]:
import numpy as np

Let us first define a Python list containing the ages of 6 people

## took some hypothetical values

In [2]:
age_list= [8,34,20,14,67,26]
print(age_list)

[8, 34, 20, 14, 67, 26]


There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use np.array(<collection>)

In [4]:
age = np.array(age_list)
print(type(age))
print(age)

<class 'numpy.ndarray'>
[ 8 34 20 14 67 26]


In [5]:
print(age)
print("Size:\t" , age.size)
print("Shape:\t", age.shape)

[ 8 34 20 14 67 26]
Size:	 6
Shape:	 (6,)


In [7]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


Multi-dim

Now let us define a new list containing the weights of these 6 people.

In [8]:
weight_list = [16, 45, 84, 56, 64, 106]
print(weight_list)

[16, 45, 84, 56, 64, 106]


Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [10]:
people = np.array([age_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[  8  34  20  14  67  26]
 [ 16  45  84  56  64 106]]
Size:	 12
Shape:	 (2, 6)


In [11]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)


People:	 [[  8]
 [ 34]
 [ 20]
 [ 14]
 [ 67]
 [ 26]
 [ 16]
 [ 45]
 [ 84]
 [ 56]
 [ 64]
 [106]]
Size:	 12
Shape:	 (12, 1)


Exercise 1






The first thing we want to do is import numpy

In [ ]:
import numpy as np

In [12]:
value1=[7, 9, 65, 33, 85, 99]
print(value1)

[7, 9, 65, 33, 85, 99]


In [27]:
value3 = np.array(value1)
value3

array([ 7,  9, 65, 33, 85, 99])

EXERCISE 2

In [36]:
value2=np.array([[1,2,4],[2,3,0],[0,5,1]])

In [37]:
value2

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [41]:
# 3 X 3 = 1 X 9 = 9 X 1
value2.reshape(9,1)


array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

ARRAY GENERATION

The np.arange() method creates a range of numbers with user defined steps between each.

In [42]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [43]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The .repeat() method will repeat an object you pas a specified number of times.

In [44]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]



The np.eye() functions will create an identity matrix/array for us.

In [45]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


OPERRATIONS


In [46]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [47]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


SPEED TEST

In [48]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [49]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

execution time of each table

In [50]:
%timeit five_times_table_lge + 5

1.24 µs ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [51]:
%timeit [e + 5 for e in fives_list]

58.3 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on ndarrays

In [52]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

Transpose

In [53]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[  8  34  20  14  67  26]
 [ 16  45  84  56  64 106]] 

[[  8  16]
 [ 34  45]
 [ 20  84]
 [ 14  56]
 [ 67  64]
 [ 26 106]]


Data type

In [54]:
people.dtype

dtype('int64')

what is the data tyoe of the below ndarray?

In [55]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [56]:
ages_with_strings.dtype

dtype('<U21')

what is the data type of this array?

In [57]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [58]:
ages_with_strings.dtype

dtype('int32')

What do you think has happened here?

In [59]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [60]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [61]:
ages_with_strings.size

126

In [62]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below

In [63]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


EXERCISE

In [64]:
arr2=np.array([[1,2,3],[23,4,6]])

In [65]:
arr2.dtype

dtype('int64')

change the data type from int to float

In [66]:
new_a=arr2.astype('float64')

In [67]:
new_a.dtype

dtype('float64')

transpose the above matrix

In [68]:
transpose=arr2.transpose()

In [69]:
transpose

array([[ 1, 23],
       [ 2,  4],
       [ 3,  6]])

In [70]:
transpose.shape

(3, 2)

In [71]:
transpose.size

6

changing the data type of boolean

In [72]:
Bool=np.array(arr2,dtype=bool)

In [74]:
Bool

array([[ True,  True,  True],
       [ True,  True,  True]])

Array Slicing Operation

In [75]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [76]:
five_times_table[0]

0

In [77]:
five_times_table[-1]

50

In [78]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [79]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [81]:
print(people)
people[:3, :3]

[[  8  34  20  14  67  26]
 [ 16  45  84  56  64 106]]


array([[ 8, 34, 20],
       [16, 45, 84]])

EXERCISE

In [82]:
zer=np.zeros(50)

In [83]:
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
repeat=np.repeat(2,20)

In [86]:
repeat

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [89]:
import math
arr3=np.arange(0, math.pi, 0.1)

In [90]:
arr3

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

We can reverse an array by using .flip() or by using the :: operator.

In [91]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [92]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [93]:
five_times_table[0::3]

array([ 0, 15, 30, 45])

EXERCISE

In [94]:
array4=np.array([1,2,3,4,5,6,7])

In [95]:
flip=np.flip(array4)

In [96]:
flip

array([7, 6, 5, 4, 3, 2, 1])

keep every 4 element

In [97]:
keep=array4[0::4]

In [98]:
keep

array([1, 5])

In [ ]:
#every second element from last

In [99]:
reverse=array4[-1::-2]

In [100]:
reverse

array([7, 5, 3, 1])

stats

In [102]:
np.array([1.65432, 5.98765]).round(2)



array([1.65, 5.99])

In [104]:
nums = np.arange(0, 4, 0.2555)

In [107]:
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

EXERCISE

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places

In [108]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


RANDOM

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [109]:
flip3=np.random.choice([0,1],10)

In [110]:
flip3

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1])

In [111]:
a=np.random.rand(10,20,9)

In [112]:
a

array([[[0.97971497, 0.89015738, 0.30860749, ..., 0.23800287,
         0.76038635, 0.14138892],
        [0.25543212, 0.32474763, 0.91535014, ..., 0.14770136,
         0.56378993, 0.23157561],
        [0.20909877, 0.91209216, 0.9637953 , ..., 0.41242254,
         0.55131511, 0.01762692],
        ...,
        [0.13097345, 0.51053102, 0.02210171, ..., 0.68790932,
         0.3034759 , 0.01880618],
        [0.96475566, 0.94087343, 0.93820315, ..., 0.18665012,
         0.76567495, 0.98036734],
        [0.47239793, 0.43441965, 0.73976989, ..., 0.95618387,
         0.6638056 , 0.78327102]],

       [[0.21557715, 0.47961665, 0.12892312, ..., 0.72856273,
         0.28255975, 0.6235401 ],
        [0.41429074, 0.75408098, 0.12941861, ..., 0.55379244,
         0.99637646, 0.44856768],
        [0.81799029, 0.37260886, 0.20406868, ..., 0.66670428,
         0.4027581 , 0.69589472],
        ...,
        [0.45345342, 0.37628333, 0.04778697, ..., 0.69353244,
         0.67988834, 0.05894898],
        [0.8

In [113]:
np.random.rand(1,2,3)

array([[[0.42140593, 0.78110325, 0.3247272 ],
        [0.52251206, 0.51671029, 0.9445959 ]]])

We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()

mean and standard deviation

In [114]:
mu, sigma = 0, 0.1 
s = np.random.normal(mu, sigma, 1000)

In [115]:
s

array([-9.07352155e-02, -1.17760793e-01, -5.03233698e-02,  1.81622195e-02,
       -7.10836991e-02,  1.90380548e-01, -4.44310659e-02, -6.88670125e-03,
        6.39581168e-02,  2.06916860e-01,  1.69491313e-02, -1.77576849e-01,
       -5.62605260e-02, -7.30702323e-02, -8.51597518e-03,  9.92371371e-02,
       -4.27009652e-02,  1.18540691e-01,  1.02817114e-01, -1.07851492e-01,
        6.42210111e-02,  1.00306445e-01, -6.35917725e-02,  1.91319045e-01,
        9.38744890e-03, -2.01413511e-01,  4.58950657e-02,  8.65598775e-02,
        7.02892823e-02,  1.11723881e-01,  8.50428517e-02, -3.57106007e-02,
        1.63643028e-01,  4.48952137e-02, -4.64592141e-02, -1.02929426e-01,
       -6.49335098e-02, -5.86004388e-02, -1.93007281e-02, -1.11782934e-01,
       -2.83679897e-02, -5.34875946e-02,  2.49682275e-01, -1.22178380e-01,
        1.10502087e-01,  7.66701619e-02,  3.82453473e-02,  5.52051626e-02,
       -7.58618478e-02, -7.90319659e-02,  5.36870262e-03,  1.55806626e-02,
        1.14353499e-01, -

EXERCISE

Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws. Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.

In [116]:
np.random.choice([1,2,3,4,5,6],10)

array([1, 6, 4, 5, 2, 5, 5, 4, 1, 4])

In [117]:
toss=np.random.choice(['Head','Head','Tail'],10)

In [119]:
toss

array(['Tail', 'Tail', 'Head', 'Head', 'Head', 'Tail', 'Head', 'Tail',
       'Head', 'Head'], dtype='<U4')